apiVersion: apps/v1
kind: Deployment
metadata:
  name: paraview-deployment
  labels:
    app: paraview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paraview
  template:
    metadata:
      labels:
        app: paraview
    spec:
      containers:
      - name: paraview
        image: lvxuxin/paraview:0101
        ports:
        - containerPort: 80
