apiVersion: v1
kind: Service
metadata:
  name: trame-app-service
spec:
  selector:
    app: trame-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      NodePort: 2357
  type: NodePort
